@startuml

title __01_TASKS's Class Diagram__\n

  namespace tasks.controller {
    class tasks.controller.Controller {
    }
  }
  

  namespace tasks.controller {
    class tasks.controller.NewEditController {
    }
  }
  

  namespace tasks.controller {
    class tasks.controller.Notificator {
    }
  }
  

  namespace tasks.controller {
    class tasks.controller.TaskInfoController {
    }
  }
  

  namespace tasks.model {
    class tasks.model.ArrayTaskList {
    }
  }
  

  namespace tasks.model {
    class tasks.model.LinkedTaskList {
    }
  }
  

  namespace tasks.model {
    class tasks.model.Task {
    }
  }
  

  namespace tasks.model {
    abstract class tasks.model.TaskList {
    }
  }
  

  namespace tasks.model {
    class tasks.model.TasksOperations {
    }
  }
  

  namespace tasks.services {
    class tasks.services.DateService {
    }
  }
  

  namespace tasks.services {
    class tasks.services.TaskIO {
    }
  }
  

  namespace tasks.services {
    class tasks.services.TasksService {
    }
  }
  

  namespace tasks.view {
    class tasks.view.Main {
    }
  }
  

  tasks.controller.Controller o-- tasks.services.DateService : dateService
  tasks.controller.Controller o-- tasks.services.TasksService : service
  tasks.controller.NewEditController o-- tasks.model.Task : currentTask
  tasks.controller.NewEditController o-- tasks.services.DateService : dateService
  tasks.controller.NewEditController o-- tasks.services.TasksService : service
  tasks.model.ArrayTaskList -up-|> tasks.model.TaskList
  tasks.model.LinkedTaskList -up-|> tasks.model.TaskList
  tasks.model.LinkedTaskList o-- tasks.model.LinkedTaskList.Node : last
  tasks.model.Task .up.|> java.io.Serializable
  tasks.model.Task .up.|> java.lang.Cloneable
  tasks.model.TaskList .up.|> java.io.Serializable
  tasks.model.TaskList .up.|> java.lang.Iterable
  tasks.services.DateService o-- tasks.services.TasksService : service
  tasks.services.TasksService o-- tasks.model.ArrayTaskList : tasks
  tasks.view.Main -up-|> javafx.application.Application
  tasks.view.Main o-- tasks.model.ArrayTaskList : savedTasksList
  tasks.view.Main o-- tasks.services.TasksService : service


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
